website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "butuz"

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    return app

website/auth.py
from flask import Blueprint

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return "<p>Login</p>"

@auth.route('/logout')
def logout():
    return "<p>logout</p>"

@auth.route('sign-up')
def sign_up():
    return "<p>INFO ABOUT PERSON<p>"

website/views.py
from flask import (
    Blueprint,
    render_template,
    send_from_directory,
    url_for,
    redirect,
    session,
    flash,
    request,
)
import os

views = Blueprint("views", __name__)

main_bio = """
Abu Pashaev, born on June 9, 1966, in the village of Chechen-Aul, Chechen-Ingush ASSR, initiated his artistic journey at an early age. Following the completion of his secondary education, he served as an instructor in drawing and drafting at his hometown school. In 1984, he was conscripted into the Soviet Army.

Post his military service, he enrolled in an art school and graduated with distinction, specializing in graphic design. Embarking on a professional trajectory, he explored diverse organizational roles, honing his artistic style, and eventually establishing himself as a freelance artist. Pashaev sought guidance from esteemed artists in the Chechen Republic, including I.N. Petrov, B.G. Radchenko, V.S. Grigoriev, among others.

In 1997, he earned his degree in art and graphic design from Chechen State Pedagogical Institute, obtaining certification as an artist. Concurrently, in the early 1980s, he delved into Eastern martial arts, coupled with a profound interest in philosophy.

By 1990, Pashaev had completed Ushu instructor courses in the "Gymnastics" section, securing diplomas as a judge and instructor. Distinctively, he crafted his own style, "Wind," amalgamating elements from the jaguar and hawk within the framework of the "Hung Gar" style.

In 1984, Pashaev unveiled a series of works titled "You Don't Know How Painful It Is!" primarily comprised of graphic pieces utilizing 3 to 7 colors. Functioning as a graphic artist, many of Pashaev's creations depict a intricate inner world, bearing titles like "Scream," "Pain," "Apocalypse," "The Reverse Side of the Day," "Flickering Shadow of the Wind," "You Don't Know How Painful It Is," and "Requiem for Mozart." These pieces serve as monologues, dialogues, and reflections on self.

For Pashaev, art metamorphosed into an expression of pain and sorrow. His works exude a cold and desolate ambiance – lonely moths navigating towards light, confronting imminent demise; a body mourning the soul; a mother's visage marked by sorrow; an unborn child destined to comprehend evil and embrace goodness. His figures, weathered by life, embody solitude.

In his works, A. Pashaev communicates succinctly, yet behind his silence lies a depth of emotions and talent. The uniqueness of each piece demands substantial effort and considerable creative tension. Pashaev's creations encapsulate a process of self-discovery.

Abu Pashaev's inaugural solo exhibition in 1992 at Chechen State Pedagogical Institute, titled "Atomic Heart of My Mom," drew significant attention due to its distinctive nomenclature.
"""
bio_gallery = """

Participation in Exhibitions:
1992: Solo exhibition "Atomic Heart of My Mom," Grozny.

1993: First exhibition "Premonition of the Civil War," Grozny.

1996: Solo exhibition "Silent Protest Against Violence," Chechen-Aul.

1997: Solo exhibition "Wounded Flowers," Chechen-Aul.

1993: Solo exhibition "The Face of War," Nazran.

2003: Solo exhibition "The Face of War," Czech Republic, Prague.

2004: Reporting exhibition "Optimistic Reflection of the Past," Grozny.

2007: Regional exhibition "Peace to the Caucasus," Grozny.

2008: Zonal exhibition "Sochi - 2008," Sochi.

2009: Joint exhibition of Chechen artists at the State Duma, Moscow.

2011: Joint exhibition of artists from the Chechen Republic, City Duma, Saratov.

2011: Exhibition "Apotheosis of History," National Museum of the Chechen Republic (with Merited Artist of the Chechen Republic V.V. Zauraev), Grozny.

2011: Exhibition-competition "The Scream in Art," Maykop.

2012: Zonal exhibition, Rostov-on-Don.

2013: Participation in the VIII International Art Symposium "Tales of Love" (presentation of 2 works), Yelabuga.

2013: Exhibition-competition "Hand in Art," Maykop.

2013: XI Regional Exhibition "Southern Russia," Grozny.
All-Russian exhibition, Moscow. Honorary diploma from the Ministry of Russia.
"""
about = """Структура HTML:
Ваш HTML-код использует базовый шаблон с использованием Flask-шаблонизатора. Это обеспечивает удобство в поддержке и масштабировании вашего веб-приложения. 
Шаблон включает в себя основные элементы, такие как навигационное меню, контейнер для контента и подключение внешних библиотек, таких как Bootstrap и Font Awesome.

Навигационное меню:
Навигационное меню включает в себя четыре пункта - "Главная", "Биография", "Галерея" и "Контакты". Эти пункты предоставляют ссылки на различные разделы вашего веб-сайта. 
На мобильных устройствах навигационное меню можно скрывать и разворачивать с помощью кнопки-бургера.

Основной контент:
Основной контент размещен в блоке {% block content %}{% endblock %}. Это место, где будет вставляться уникальный контент для каждой страницы, 
расширяющей базовый шаблон. Ваш пример страницы "Главная" содержит заголовок и изображение.

Изображение:
Для вставки изображения на страницу "Главная" вы используете тег <img>. Важно убедиться, что изображение "mount.jpg" расположено в правильной директории, 
и путь к нему указан верно.

Статические файлы и скрипты:
Вы подключаете статические файлы, такие как CSS и JavaScript, для Bootstrap и Font Awesome, обеспечивая правильное оформление и интерактивность вашего веб-сайта. 
Также включен собственный скрипт "index.js".

Flask-роутинг:
В вашем Flask-приложении определен маршрут для домашней страницы ("/"), который рендерит шаблон "home.html". Это означает, 
что содержимое "home.html" будет отображаться, когда пользователь посещает главную страницу.

Этот код предоставляет основу для создания различных страниц и разделов вашего веб-сайта. Вы можете расширить его, добавляя новые страницы, контент и функциональность. 
Например, вы можете создать отдельные HTML-шаблоны для страниц "Биография", "Галерея" и "Контакты", реализовать логику обработки форм на странице "Контакты" 
с использованием Flask и т.д."""
bio1 = """Abu Pashaev, born in 1966 in Chechen-Aul, is a distinguished artist whose life journey shapes 
his profound creations. From serving in the Soviet Army to graduating in graphic design, Pashaev's diverse 
experiences manifest in his artwork. Seeking guidance from renowned Chechen artists and integrating martial arts philosophy, 
he crafted his style, "Wind." His graphic series, like "You Don't Know How Painful It Is!," explores inner worlds 
with titles such as "Scream" and "Apocalypse." Pashaev's works express universal themes of pain, solitude, and the human condition, 
showcasing his ability to convey deep emotions through a meticulous artistic process. His inaugural exhibition, 
"Atomic Heart of My Mom" (1992), marked the beginning of a significant artistic journey. Abu Pashaev emerges as an artist 
whose profound expressions resonate with the complexities of human existence."""


@views.route("/")
def home():
    return render_template("home.html", mod=about)


@views.route("/bio")
def bio():
    return render_template("bio.html", text=main_bio, bio=bio1)


@views.route("/view_image/<filename>")
def view_image(filename):
    path = os.path.join("static", "larger_images", filename)
    print("Trying to serve image from path:", path)
    return send_from_directory("static/larger_images", filename)


@views.route("/gallery")
def gallery():
    gallery_images = ["blue.jpg", "yellow.jpg", "bridge.jpg"]
    return render_template("gallery.html", gallery_images=gallery_images)


@views.route("/contacts")
def contacts():
    return render_template("contacts.html")


@views.route("/lang/<lang>")
def set_language(lang):
    session["lang"] = lang
    flash(_("Your changes have been saved."))
    referrer = request.referrer or url_for("views.home")
    return redirect(f"{referrer}?lang={lang}")

website/templates/bio.html
{% extends "body.html" %}

{% block title %}Bio{% endblock %}

{% block content %}
<head>
    <!-- Other head elements -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bio.css') }}">
</head>
<body>
<div class="container-fluid">
    <h2 class="text-center custom-heading "> "Nostalgia is a passing phrase of infinity." </h2>
  </div>







    <div class="row row-content">
        <div class="col-lg-6">
            <img src="{{ url_for('static', filename='Images/avatar-circle.png') }}" alt="Abu Pashaev" class="img-fluid rounded">
        </div>
        <div class="col-lg-6 text-font top-bio" style="margin-top: 150px;">
            Abu Pashaev, is a distinguished artist whose life journey shapes his profound creations. From serving in the Soviet Army to graduating in graphic design, Pashaev's diverse experiences manifest in his artwork. Seeking guidance from renowned Chechen artists and integrating martial arts philosophy, he crafted his style, "Wind." His graphic series, like "You Don't Know How Painful It Is!," explores inner worlds with titles such as "Scream" and "Apocalypse."
        </div>
    </div>

    <hr class="team_hr" style="border-bottom: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">
    <div class="white-container">
        <h1>Where Art Meets Emotion, and Every Stroke Tells a Story.</h1>
        {{ text }} 




    
    <hr class="row row-content" class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">


    <div class="row row-content">
        <div class="col-lg-6 text-center" style="font-size: 28px; margin-top: 150px;">
            Pashaev's works express universal themes of pain, solitude, and the human condition, showcasing his ability to convey deep emotions through a meticulous artistic process. His inaugural exhibition, "Atomic Heart of My Mom" (1992), marked the beginning of a significant artistic journey. Abu Pashaev emerges as an artist whose profound expressions resonate with the complexities of human existence.
        </div>  
            <!-- Image Slider -->
            <div class="slider-container">
                <div class="slides">
                    <div class="slide" onclick="enlargeImage('{{ url_for('static', filename='Images/bio/schoolStone.jpg') }}')">
                        <img src="{{ url_for('static', filename='Images/bio/schoolStone.jpg') }}" alt="Blue">
                    </div>
                    <div class="slide" onclick="enlargeImage('{{ url_for('static', filename='Images/bio/schoolCeramic.jpg') }}')">
                        <img src="{{ url_for('static', filename='Images/bio/schoolCeramic.jpg') }}" alt="Bridge">
                    </div>
                    <div class="slide" onclick="enlargeImage('{{ url_for('static', filename='newspapers/newspaper4.jpg') }}')">
                        <img src="{{ url_for('static', filename='newspapers/newspaper4.jpg') }}" alt="Back">
                    </div>
                    <div class="slide" onclick="enlargeImage('{{ url_for('static', filename='newspapers/newspaper5.jpg') }}')">
                        <img src="{{ url_for('static', filename='newspapers/newspaper5.jpg') }}" alt="Sun">
                    </div>
                </div>
    
            
                <!-- Dots to count images -->
                <div class="dots-container">
                    {% for _ in range(1, 4) %}
                        <div class="dot" onclick="currentSlide({{ loop.index }})"></div>
                    {% endfor %}
                </div>   
            </div>
        </div>
    </div>




    <hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">

      
  
    <div class="row row-content adjustable-margin" style="color: rgb(237, 236, 236);">
        <div class="col-lg-6">
            <h1>BOTTOM TEXT</h1>
            {{ mod }}
            <div class="row">
                <div class="col-lg-6">
                    <img src="static/Images/sign.png" alt="Sign" style="width: 100%;">
                </div>
                <div class="col-lg-6">
                    <img src="static/Images/sign.png" alt="Sign" style="width: 100%;">
                </div>
            </div>
        </div>
    </div>



    <hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 100px 0;">
    <div class="cream-container">
        <div class="left-section">
            <img src="{{ url_for('static', filename='Images/bio/school1.jpg') }}" alt="Image 10" class="image">
        </div>
        <div class="right-section">
            <div class="text">
                "Discover the artistic world of Abu Pashaev."
            </div>
            <button class="explore-button">Explore</button>
        </div>
    </div>
    

    <hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">



    <div class="row row-content">
        
        <div class="col-lg-6 order-lg-1">
            <img src="{{ url_for('static', filename='Images/freeman.png') }}" alt="Freeman" class="img rounded" style="width: 100%;">
        </div>  
    </div>

    <hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 0px 0;">




    
    <div class="row row-content">
        <div class="col-lg-6 mx-auto text-center">
            <h1>Art Exhibitions</h1>
        </div>
    </div>
</div>




<div class="bg-dark text-white text-font" style="width: 100%; padding: 40px;">
    <table style="border-collapse: collapse; width: 80%; margin: 0 auto;">
    
    <tr>
        <td>1992</td>
        <td>Atomic Heart of My Mom</td>
        <td>Grozny, Russia</td>
    </tr>
    <tr>
        <td>1993</td>
        <td>Premonition of the Civil War</td>
        <td>Grozny, Russia</td>
    </tr>
    <tr>
        <td>1996</td>
        <td>Silent Protest Against Violence</td>
        <td>Chechen-Aul, Russia</td>
    </tr>
    <tr>
        <td>1997</td>
        <td>Wounded Flowers</td>
        <td>Chechen-Aul, Russia</td>
    </tr>
    <tr>
        <td>1993</td>
        <td>The Face of War</td>
        <td>Nazran, Russia</td>
    </tr>
    <tr>
        <td>2003</td>
        <td>The Face of War</td>
        <td>Prague, Czech Republic</td>
    </tr>
    <tr>
        <td>2004</td>
        <td>Optimistic Reflection of the Past</td>
        <td>Grozny, Russia</td>
    </tr>
    <tr>
        <td>2007</td>
        <td>Peace to the Caucasus</td>
        <td>Grozny, Russia</td>
    </tr>
    <tr>
        <td>2008</td>
        <td>Sochi - 2008</td>
        <td>Sochi, Russia</td>
    </tr>
    <tr>
        <td>2009</td>
        <td>Chechen Artists at the State Duma</td>
        <td>Moscow, Russia</td>
    </tr>
    <tr>
        <td>2011</td>
        <td>Artists from the Chechen Republic</td>
        <td>Saratov City Duma, Russia</td>
    </tr>
    <tr>
        <td>2011</td>
        <td>Apotheosis of History (with V.V. Zauraev)</td>
        <td>Grozny, Russia</td>
    </tr>
    <tr>
        <td>2011</td>
        <td>Scream in Art</td>
        <td>Maykop, Russia</td>
    </tr>
    <tr>
        <td>2012</td>
        <td>Zonal Exhibition</td>
        <td>Rostov-on-Don, Russia</td>
    </tr>
    <tr>
        <td>2013</td>
        <td>VIII International Art Symposium "Tales of Love"</td>
        <td>Yelabuga, Russia</td>
    </tr>
    <tr>
        <td>2013</td>
        <td>Hand in Art</td>
        <td>Maykop, Russia</td>
    </tr>
    <tr>
        <td>2013</td>
        <td>XI Regional Exhibition "Southern Russia"</td>
        <td>Grozny, Russia</td>
    </tr>
    </table>
</div>


<hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 100px 0;">
<div class="row-bottom">
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
</div>

<div class="iconbutton">
    <a href="#bio">
      <!--Add the code here for the logo to appear and the icon to be actionable-->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" width="63px">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 11.25l-3-3m0 0l-3 3m3-3v7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    </a>
  </div>

<!-- Enlarged Image Modal -->
<div class="enlarged-modal" onclick="closeEnlarged()">
    <span class="close-button" onclick="closeEnlarged()">&times;</span>
    <img id="enlargedImg" alt="">
</div>

</body>



<script src="static/js/bioScript.js"></script>
{% endblock %}

website/templates/body.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Top section -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/body.css') }}" />
    <link href="https://fonts.googleapis.com/css2?family=Calibri:wght@400;300&display=swap" rel="stylesheet">
</head>

<body> 
 <!-- Main navbar -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="navbar-nav mx-auto">
            <a class="nav-item nav-link" id="home" href="/">MAIN</a>
            <a class="nav-item nav-link" id="bio" href="/bio">BIOGRAPHY</a>
            <a class="nav-item nav-link" id="gallery" href="/gallery">GALLERY</a>
            <a class="nav-item nav-link" id="contacts" href="/contacts">CONTACTS</a>
        </div>

        <!-- Language Switch Button -->
        <div class="navbar-nav">
            <div class="language-switch ml-auto">
                {% if session['lang'] == 'en' %}
                <a href="{{ url_for('views.set_language', lang='ru') }}">RU</a>
                {% else %}
                <a href="{{ url_for('views.set_language', lang='en') }}">EN</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Main content -->
    <div style="margin: 5%; margin-left: 13%; margin-right: 13%;">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer section -->
    <footer class="footer-section botBorder">
        <div class="container-fluid">
            <div class="row no-gutters">
                <div class="col-12 col-md text-center footerText social">
                    All works © Abu Pashaev
                </div>

                <div class="col-12 col-md text-center footerText social">
                    E
                    <a href="mailto:info@AbuPashaev.com" target="_blank"><img
                        src="static/Images/logos/mail.png" alt="EmailSign"></a>ail
                </div>
                
                <div class="col-12 col-md text-center footerText social">
                    <a href="https://www.instagram.com/pashaev.abu/" target="_blank"><img
                            src="static/Images/logos/instagram.png" alt="Instagram"></a>
                </div>

                <div class="col-12 col-md text-center footerText social">
                    <a href="https://www.instagram.com/pashaev.abu/" target="_blank">Buy me a Coffee<img
                            src="static/Images/logos/coffee.png" alt="Donate"></a>
                </div> 
                <div class="col-12 col-md text-center footerText social">
                    <a href="https://www.instagram.com/pashaev.abu/" target="_blank">DONATE<img
                            src="static/Images/logos/donate.png" alt="Donate"></a>
                </div> 
            </div>
        </div>
    </footer>
</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
</html>

website/templates/home.html
{% extends "body.html" %}
{% block title %}HOME{% endblock %}
{% block content %}
<head>
    <!-- Other head elements -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
</head>

<div class="container-fluid">
    <h1 class="text-center larger-name"> Abu Pashaev </h1>
    <h2 class="text-center custom-heading "> "Nostalgia is a passing phrase of infinity." </h2>
  </div>

<div class="body2">
    <div id="image-track" data-mouse-down-at="0" data-prev-percentage="0">
      <img class="images" src="static/Images/homeSlides/IMG26.jpg" draggable="false" />
      <img class="images" src="static/Images/homeSlides/IMG27.jpg" draggable="false" />
      <img class="images" src="static/Images/homeSlides/IMG28.jpg" draggable="false" />
      <img class="images" src="static/Images/homeSlides/IMG29.jpg" draggable="false" />
      <img class="images" src="static/Images/homeSlides/IMG30.jpg" draggable="false" />
    </div>
  </div>


<hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">

<div class="cream-container">
    <div class="left-section">
        <img src="{{ url_for('static', filename='Images/freeman.png') }}" alt="Image 10" class="image">
    </div>
    <div class="right-section">
        <div class="text" style="margin-left: 40%; width: 80%; font-size: 24px;">
            "Curious to learn more about the creative mind shaping these captivating artworks? Click below to explore the inspiring journey and unique perspective of our talented artist. "
        </div>
        <a href="https://www.google.com" class="explore-button textFont">About Artist</a>
    </div>
</div>


<hr class="team_hr" style="border-top: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">



<div class="row row-content">
    <div class="carouselText">
        An Esoteric Perspective on Ancestral Symbols
    </div>
    
<main id="carousel">
    <div class="item">
        <img src="{{ url_for('static', filename='Images/LatestIMG/Img1.jpg') }}" alt="Image 1">
    </div>
    <div class="item">
        <img src="{{ url_for('static', filename='Images/LatestIMG/Img2.jpg') }}" alt="Image 2">
    </div>
    <div class="item">
        <img src="{{ url_for('static', filename='Images/LatestIMG/Img3.jpg') }}" alt="Image 3">
    </div>
    <div class="item">
        <img src="{{ url_for('static', filename='Images/LatestIMG/Img4.jpg') }}" alt="Image 4">
    </div>
    <div class="item">
        <img src="{{ url_for('static', filename='Images/LatestIMG/Img5.jpg') }}" alt="Image 5">
    </div>
</main>
</div>

<hr class="team_hr" style="border-bottom: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">

<div class="cream-container2 row-container">
    <div class="left-section2" style="margin-right: 13%;">
        <div class="text2 textFont" style="font-size: 36px; color: #ec994b;">
            "Discover the artistic world of Abu Pashaev."
        </div>
        <button class="gallery-button textFont" >GALLERY</button>
    </div>
    <div class="right-section2">
        <img src="{{ url_for('static', filename='Images/school.jpg') }}" alt="Image 10" class="image2">
    </div>
</div>

<hr class="team_hr" style="border-bottom: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">

<p class="p textFont">
    <span>
        <strong>
            Need more help?
        </strong>
    </span>
</p>


<button class="contact-button">Contact Us</button>


<hr class="team_hr" style="border-bottom: 1px solid rgba(255, 255, 255, 0.5); margin: 50px 0;">

<div class="row-bottom" style="display: flex; justify-content: space-between; margin-left: 2%; margin-right: 2%;">
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
    <div>
        <p><span style="font-size:20px;"><img alt="Value creation" src="static/Images/signGif.gif" style="height: 120px; width: 120px;"></span></p>
    </div>
</div>

<div class="iconbutton">
    <a href="#home">
      <!--Add the code here for the logo to appear and the icon to be actionable-->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" width="63px">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 11.25l-3-3m0 0l-3 3m3-3v7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    </a>
  </div>

<script src="static/js/homeScript.js"></script>

{% endblock %}